Fix set_version documentation
The documented way to set the version isn't quite correct - the method name doesn't include the `=`.

The error was:
```
undefined method `set_version=' for Chromedriver:Module
Did you mean?  set_version (NoMethodError)
/Users/jamiecobbett/code/livestax/config/initializers/chromedriver.rb:17:in `<top (required)>'
```